// Generated by generate-api-contracts.swift
// Do not edit directly

import Foundation

public enum APIEndpoint {
    case getVenues
    case getVenue(id: String)
    case getDrinks(venueId: String)
    case getPasses
    case purchasePass(venueId: String)
    case placeOrder(venueId: String, drinkIds: [String])
    case profile
    case updateProfile(name: String, email: String, phoneNumber: String?)
    
    public var path: String {
        switch self {
        case .getVenues:
            return "/venues"
        case .getVenue(let id):
            return "/venues/\(id)"
        case .getDrinks(let venueId):
            return "/venues/\(venueId)/drinks"
        case .getPasses:
            return "/passes"
        case .purchasePass:
            return "/passes/purchase"
        case .placeOrder:
            return "/orders"
        case .profile:
            return "/profile"
        case .updateProfile:
            return "/profile/update"
        }
    }
    
    public var method: String {
        switch self {
        case .getVenues, .getVenue, .getDrinks, .getPasses, .profile:
            return "GET"
        case .purchasePass, .placeOrder, .updateProfile:
            return "POST"
        }
    }
}
