// Generated by generate-api-contracts.swift
// Do not edit directly

import Foundation

public struct Venue: Codable {
    public let id: String
    public let name: String
    public let description: String
    public let address: String
    public let imageUrl: String
    public let capacity: Int
    public let currentCapacity: Int
    public let rating: Double
    public let isOpen: Bool
    public let waitTime: Int
    
    public init(id: String, name: String, description: String, address: String, imageUrl: String, capacity: Int, currentCapacity: Int, rating: Double, isOpen: Bool, waitTime: Int) {
        self.id = id
        self.name = name
        self.description = description
        self.address = address
        self.imageUrl = imageUrl
        self.capacity = capacity
        self.currentCapacity = currentCapacity
        self.rating = rating
        self.isOpen = isOpen
        self.waitTime = waitTime
    }
}

public struct Pass: Codable {
    public let id: String
    public let venueId: String
    public let userId: String
    public let type: String
    public let status: String
    
    public init(id: String, venueId: String, userId: String, type: String, status: String) {
        self.id = id
        self.venueId = venueId
        self.userId = userId
        self.type = type
        self.status = status
    }
}

public struct Drink: Codable {
    public let id: String
    public let name: String
    public let description: String
    public let price: Double
    public let imageUrl: String
    
    public init(id: String, name: String, description: String, price: Double, imageUrl: String) {
        self.id = id
        self.name = name
        self.description = description
        self.price = price
        self.imageUrl = imageUrl
    }
}

public struct UserProfile: Codable {
    public let id: String
    public let name: String
    public let email: String
    public let phoneNumber: String?
    
    public init(id: String, name: String, email: String, phoneNumber: String?) {
        self.id = id
        self.name = name
        self.email = email
        self.phoneNumber = phoneNumber
    }
}
